### ISSUE TITLE
1-us Play a song and guess the titel

### ISSUE THREAD

**Issue by Morten-Moeller** [Morten-Moeller/capstone-project#1]
## Value statement - a requirement, not a solution

As a **user**
I want to **start a Song**
so that i can **guess the title**

## Description (Text, Scribble, Wireframe, Design)

![first scribble capstone(1)](https://user-images.githubusercontent.com/74534309/120538358-b4507c00-c3e6-11eb-8b2a-35f23ab54eb9.png)

## Acceptance criteria

- [x] Play button should start the song
- [x] The text buttons should contain 3 different song titles but one must be equal to the playing song.
- [x] You can press only one button during a song 
- [x] The buttons should show red or green
- [x] After pressing the button, the song should stop
- [x] If the song ended the playback should end
- [x] Play button can start the song again but just if no song plays anymore

## Tasks

- [x] Feature branch
- [x] Text Button component w/ storybook and tests
- [x] Play Page component w/ storybook and tests
- [x] Update App with components and logic

## Complexity

low
