### ISSUE TITLE
5-us Backend basic reverse-proxy

### ISSUE THREAD

**Issue by Morten-Moeller** [Morten-Moeller/capstone-project#10]
## Value statement - a requirement, not a solution

As a **user**
I need to **play the game not just local**
so i **can play anywhere**

## Description (Text, Scribble, Wireframe, Design)

Add a node express server as a Reverse-Proxy so the fetch calls would redirect thru the backend and don't have to handle the CORS-header.

## Acceptance criteria

- [ ] The Server must redirect the fetch calls

## Tasks

- [ ] Feature branch
- [ ] Install Express
- [ ] Build up a node server
- [ ] Build routs for iTunes

## Complexity

low
