### ISSUE TITLE
7-us Backend with additional functionality

### ISSUE THREAD

**Issue by Morten-Moeller** [Morten-Moeller/capstone-project#11]
## Value statement - a requirement, not a solution

As a **user**
I need to **start the game faster**
so i **can play even longer**

## Description (Text, Scribble, Wireframe, Design)

Add the whole fetch to the backend and save the response data local, so different user can access them after first fetch of a playlist.

## Acceptance criteria

- [x] Save data in the backend
- [x] Preform a fetch for selected playlists 

## Tasks

- [x] Feature branch
- [x] Add logic to the backend

## Complexity

medium
