### ISSUE TITLE
5-us Select playlists

### ISSUE THREAD

**Issue by Morten-Moeller** [Morten-Moeller/capstone-project#12]
## Value statement - a requirement, not a solution

As a **user**
I need to **have more playlists**
so i **can play with music i like**

## Description (Text, Scribble, Wireframe, Design)

![us7](https://user-images.githubusercontent.com/74534309/121666803-f1350680-caa9-11eb-8794-1149b9b1800b.png)

![us7-2](https://user-images.githubusercontent.com/74534309/121669871-19723480-caad-11eb-92aa-79df61b82a31.png)

## Acceptance criteria

- [ ] Have a new first page
- [ ] Have an option to select a playlist
- [ ] The player should only play songs from the selected playlist
- [ ] A button to start with the selected playlist
- [ ] A back button from player to select a new list
- [ ] The playlist should be fetched

## Tasks

- [ ] Feature branch
- [ ] Add StartPage component
- [ ] Add Header component
- [ ] Add logic

## Complexity

medium
