### ISSUE TITLE
6-us Add score, name and history

### ISSUE THREAD

**Issue by Morten-Moeller** [Morten-Moeller/capstone-project#13]
## Value statement - a requirement, not a solution

As a **user**
I need to **have a score, name and history**
so i **can play more competitive**

## Description (Text, Scribble, Wireframe, Design)

![us8](https://user-images.githubusercontent.com/74534309/121668954-1d518700-caac-11eb-96a4-196a13d169b1.png)

## Acceptance criteria

- [ ] Have 3 pages
- [ ] Navigation
- [ ] History should be saved to local storage
- [ ] If back button is used the name should still be set
- [ ] If you restart a playlist you start by 0 score
- [ ] Score should be time based
- [ ] Playlists should be a tag-list
- [ ] The active listitem should change color

## Tasks

- [ ] Feature branch
- [ ] State for Name
- [ ] Load and save from/to local storage
- [ ] Add input for name
- [ ] Add a pretty date for the history
- [ ] Add HistoryPage component
- [ ] Add HistoryEntry component
- [ ] Add logic for score and counting points

## Complexity

medium
