### ISSUE TITLE
2-us Timer

### ISSUE THREAD

**Issue by Morten-Moeller** [Morten-Moeller/capstone-project#2]
## Value statement - a requirement, not a solution

As a **user**
I need to **see how much time left for guessing**
so that i **don't miss the vote** 

## Description (Text, Scribble, Wireframe, Design)

![first scribble capstone(2)](https://user-images.githubusercontent.com/74534309/120539972-718fa380-c3e8-11eb-9810-59607df44aae.png)

## Acceptance criteria

- [x] Get the playback time
- [x] The timer should update every second
- [x] After the song the play button should be shown again

## Tasks

- [x] Feature branch
- [x] Create Timer component
- [x] Get timer instead of play button after click

## Complexity

low
