### ISSUE TITLE
8-us useMqtt hook

### ISSUE THREAD

**Issue by Morten-Moeller** [Morten-Moeller/capstone-project#20]
## Value statement - a requirement, not a solution

To prevent a to large user story, i just took this one, to create a custom Hook that hands me all needed functions for the server connection via mqtt.

## Acceptance criteria

- [ ] Connection to the Server
- [ ] Subscribe a room
- [ ] Send messages
- [ ] Get message

## Tasks

- [ ] Feature branch
- [ ] useMqtt hook
- [ ] test with local server
- [ ] .env for server credentials 

## Complexity

medium
