### ISSUE TITLE
11-us Implement Multiplayer

### ISSUE THREAD

**Issue by Morten-Moeller** [Morten-Moeller/capstone-project#21]
## Value statement - a requirement, not a solution

As a **user**
I need to **play against others**
so i **can show off!**

## Description (Text, Scribble, Wireframe, Design)

I connect the useMqtt hook with the App logic

![us9](https://user-images.githubusercontent.com/74534309/122897108-fca9ec80-d349-11eb-957c-3e7e5af4f075.png)

## Acceptance criteria

- [ ] Room name as subscriber topic 
- [ ] If room is empty use single player
- [ ] If room is given, then multiplayer
- [ ] All players must have the same song
- [ ] All players must have the same answers

## Tasks

- [ ] Feature branch
- [ ] Room name input
- [ ] Connect the SinglePlayPage
- [ ] Connect the MultiPlayPage

## Complexity

medium
