### ISSUE TITLE
9-us SinglePlayPage

### ISSUE THREAD

**Issue by Morten-Moeller** [Morten-Moeller/capstone-project#23]
## Value statement - a requirement, not a solution
I want to prepare the multiplayer, for now it shouldn't change anything for the user.
But to keep the UserStotys small i add this step.

## Description (Text, Scribble, Wireframe, Design)

I want to transfer as much logic as possible into the singlePlayPage

## Acceptance criteria

- [ ] All logic for the Playlist is inside the SinglePlayPage

## Tasks

- [ ] Feature branch
- [ ] Rename PlayPage to SinglePlayPage
- [ ] Transfer usePlaylist into SinglePlayPage

## Complexity

low
