### ISSUE TITLE
10-us MultiPlayPage

### ISSUE THREAD

**Issue by Morten-Moeller** [Morten-Moeller/capstone-project#24]
## Value statement - a requirement, not a solution

This is going to be a  part of larger changing and would be for the user in the next UserStoy

## Description (Text, Scribble, Wireframe, Design)

I want to create a MultiPlayPage with all the logic for the multiplayer in it.

## Acceptance criteria

- [ ] Decides who is the Host
- [ ] Send URL and answers via mqtt 
- [ ] Take URL and answers via mqtt and process it
- [ ] Start the game if everyone is ready
- [ ] Host has a start button.

## Tasks

- [ ] Feature branch
- [ ] Add MultiPlayPage
- [ ] Add all the logic

## Complexity

high
