### ISSUE TITLE
3-us Check A11y

### ISSUE THREAD

**Issue by Morten-Moeller** [Morten-Moeller/capstone-project#3]
## Value statement - a requirement, not a solution

As a **person who is blind**
I must be** able to guess quickly**
so that **equal opportunities prevail**

## Description (Text, Scribble, Wireframe, Design)

Try to optimize the navigation between the options 

## Acceptance criteria

- [x] Screen reader should give a good overview
- [x] The navigation should be easy to use
- [x] Buttons should be usable by shortcut
- [x] There should be an introduction to shortcuts

## Tasks 

- [x] Feature branch
- [x] Add shortcut for A, B, C buttons with 1, 2, 3 and a , b, c
- [x] Check page with screen reader 
- [x] Add introduction for the shortcuts

## Complexity

low
