### ISSUE TITLE
4-us More songs

### ISSUE THREAD

**Issue by Morten-Moeller** [Morten-Moeller/capstone-project#4]
## Value statement - a requirement, not a solution

As a **user**
I need to **have more then one song**
so i **can play more then one round**

## Description (Text, Scribble, Wireframe, Design)

Add an array of songs and play a random song on play.
After the song has finished the song shouldn't be played again.

## Acceptance criteria

- [x] Play a song just once
- [x] Change button text 
- [x] a random button should contain the right answer
- [x] If all songs are played reset the list and start again

## Tasks

- [x] Feature branch
- [x] Create a local JSON file with around 20 different titles
- [x] Fetch and parse a random title
- [x] Check if the song was played since page reload
- [x] Check if the preview is available otherwise get a new song
- [x] When the song ends, show the play button with the new song attached to it
- [x] Update the text buttons with new options for guessing

## Complexity

medium
